<?php
$om = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $om->get('Magecomp\Mobilelogin\Helper\Data');
?>
<div id="myModal" class="modal ajax-login-form">
 <!-- Modal content -->



  <div class="<?php if($helper->getLayoutType()){echo 'ultimate';}else{ echo 'mobile-modal-content';} ?>">
      <?php include ($block->getTemplateFile('Magecomp_Mobilelogin::image.phtml')) ?>
<div class="<?php if($helper->getLayoutType()) echo 'right' ?>">
    <div class="<?php if($helper->getLayoutType()){echo 'closediv-ultimate';}else{ echo 'closediv';} ?> "><span class="close"></span></div>
    <div class="ajax-login-conten">
    	<div  id="ajaxlogin-login-window" class="login-window account-login ajaxloginphtml">
        	<form action="<?php echo $block->getUrl('mobilelogin/index/ajaxlogin') ?>" data-mage-init='{"validation": {}}' method="post" id="mobile-login-form" class="scaffold-form">
                <?php echo $block->getBlockHtml('formkey'); ?>
               	  <div class="updatepasssuccess success" style="display:none">
                        <span ><?php echo __("Password has been Updated Successfully.");?></span>
                    </div>
                <div class="sendemail success" style="display:none">
                </div>
                    <div class="emailpasswrong error1" style="display:none">
                        <span ></span>
                    </div>

                 <div class="page_title">
                    <span><?php echo __('Login') ?></span>
                </div>	
                  <div class="content">
                    <ul class="form-list" style="padding:0">
                        <li>
                            <div class="input-box">
                                <span style="position:relative"> <input type="text"  name="login[username]" value="" id="mobile-login-email" placeholder="<?php echo __('Email Address/Mobile Number *') ?>" class="input-text required-entry " title="<?php echo __('Email Address') ?>" > <span class="user-icon"></span> </span>
                            </div>
                            <div class="notice" style="margin-left: 5px">Mobile No. With Country Code i.e 919898989898</div>
                        </li>
                        <li>
                            <div class="input-box">
                                <span style="position:relative"> <input type="password" name="login[password]" placeholder="<?php echo __('Password') ?>"  id="mobile-login-pass" title="<?php echo __('Password') ?>" /><span class="pass-icon"></span></span>
                            </div>
                        </li>

                    </ul>
           	 	</div>
                <div class="<?php if($helper->getTemplateImage()){echo 'buttons-set-ultimate';}else{ echo 'buttons-set';} ?>">
	                <div class="register">
                        Don’t have an Account? <a class="createlinking" href="#" id="register"><?php echo __("Register");?></a>
                    </div>     
                    <div class="forogotlink">
						 <a class="forgotlinking" href="#"><?php echo __("Forgot Password ?");?></a>
                    </div>     
              </div>
              <div class="loginlink">
                <button type="button" class="mobbtn primary" title="<?php echo __('Login') ?>" name="send" id="loginsubmit"><span><span><?php echo __('Login') ?></span></span></button>
				    <div class="progress-indicator"  style="display:none;">
                        <span class="please-wait" id="login-please-wait">
                            <img src="<?php echo 
							$block->getViewFileUrl('Magecomp_Mobilelogin::images/ajax-loader.gif');?>" class="v-middle" alt=""/>
                        </span>
                    </div>
                </div>
                
            </form>
		</div>
    </div>
</div>
  </div>
</div>
