<?php
$om = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $om->get('Magecomp\Mobilelogin\Helper\Data');
?>
<div id="myModal" class="modal ajax-login-form">
  <!-- Modal content -->
    <div class="<?php if($helper->getLayoutType()){echo 'ultimate';}else{ echo 'mobile-modal-content';} ?>">
        <?php include ($block->getTemplateFile('Magecomp_Mobilelogin::image.phtml')) ?>
        <div class="<?php if($helper->getLayoutType()) echo 'right' ?>">
    <div class="closediv"><span class="close"></span></div>
    <div class="ajax-login-conten">
    	<div id="ajaxlogin-login-window" class="login-window account-login">
        	<div class="loginotpmobileget">
            		 <div class="loginotpmobbtnerror error1" style="display:none">
                        <span class=""><?php echo __("Please Enter Valid Mobile.");?></span>
                    </div>
                    <div class="loginsendotperror error1" style="display:none">
                     	<span><?php echo __("Mobile Number Doesn't Exist");?></span>
                     </div>
                      <div class="updatepasssuccess success" style="display:none">
                        <span ><?php echo __("Password has been Updated Successfully.");?></span>
                    </div>
                    <div class="sendemail success" style="display:none">
                    </div>
                    <div class="checkloginotperror error1" style="display:none">
                       <span><?php echo __("OTP Not Verified.");?></span>
	                </div>
                    <div class="emptyotp error1" style="display:none">
                        <span><?php echo __("Please enter otp");?></span>
                    </div>

                <div class="page_title">
                        <span><?php                      
                         echo __('Login') ?></span>
                    </div>
                    <div class="otp-content">

                        <input type="text" value="" id="loginotpmob" placeholder="<?php echo __('Mobile Number*') ?>" maxlength="12"/>
                        <input type="hidden" value="<?php echo $this->getUrl("mobilelogin/index/ajaxsentotpforlogin"); ?>" class="loginotp-otp-url"/>
                     </div>
                    <div class="notice" style="margin-left:44px !important;">Mobile No. With Country Code i.e 919898989898</div>
                     <div class="model-bottom">
                         <div class="submitbtnajax">
                                <input type="button" class="loginotpmobbtn mobbtn" value="<?php echo __('Send Otp') ?>" />
                         </div>
                         <div class="progress-indicator">
                             <span class="please-wait" id="login-sms-please-wait" style="display:none;">
                                <img src="<?php echo $block->getViewFileUrl('Magecomp_Mobilelogin::images/ajax-loader.gif'); ?>" class="v-middle" alt=""/>
                            </span>
                        </div>
                   </div>
             </div>
              <div class="loginotpverify" style="display:none">
                    <div class="info">
                    	<span class="title"><?php echo __('Enter One Time Password') ?></span>
                        <p><?php echo __('One Time Password (OTP) has been sent to your mobile,') ?></p>
						<p><?php echo __('please enter the same here to login.') ?></p>
                    </div>
                    <div class="otp-content">
                        <input type="password" value="" id="logintotp" placeholder="<?php echo __('OTP') ?>" maxlength="<?php echo $helper->getOtpStringlenght() ?>"/>
                         <input type="hidden" value="<?php echo $this->getUrl("mobilelogin/index/ajaxverifyOtpForLogin"); ?>" class="loginotp-verify-url" />
                        <input type="hidden" value="<?php echo $this->getUrl("customer/account/"); ?>" class="customeraccount" />
                        
                   </div>
                    <div class="model-bottom">
                        <div class="submitbtnajax">
                            <input type="button" class="loginverifyotp mobbtn" value="<?php echo __("VERIFY & lOGIN");?>" />
                        </div>
                         <div class="progress-indicator">
                             <span class="please-wait" id="login-verify-please-wait" style="display:none;">
                                <img src="<?php echo $block->getViewFileUrl('Magecomp_Mobilelogin::images/ajax-loader.gif'); ?>" class="v-middle" alt=""/>
                            </span>
                        </div>
                   </div>
            </div>
		</div>
    </div>
  </div>
 </div>
</div>
