<?php

$helper = $this->helper('Magecomp\Mobilelogin\Helper\Data');

?>

<?php 
if($this->helper('Magecomp\Mobilelogin\Helper\Data')->isEnable() == 1){ ?>
<?php if($helper->getLoginType() == 0){ ?>
 <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magecomp_Mobilelogin::ajaxlogin.phtml")->toHtml(); ?>
 <?php } else { ?>
 <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magecomp_Mobilelogin::ajaxotplogin.phtml")->toHtml(); ?>
 <?php } ?>
  <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magecomp_Mobilelogin::ajaxforgot.phtml")->toHtml(); ?>
    <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magecomp_Mobilelogin::ajaxregister.phtml")->toHtml(); ?>
  
<?php } ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magecomp_Mobilelogin/js/script": {}
        }
    }

</script>