<div class="row">
    <div class="col-md-3 message-folders">
        <?php echo $block->getChildHtml('folders')?>
    </div>
    <div class="col-md-9 message-list">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?php echo $block->getTitle();?></h3>
            </div>
            <?php echo $block->getChildHtml('message_content')?>
        </div>
    </div>
</div>