<?php $_message = $block->getMessage();?>
<div class="row">
    <div class="col-md-3 message-folders">
        <?php echo $block->getChildHtml('folders')?>
    </div>
    <div class="col-md-9 view-message">
        <div class="message-buttons">
            <button class="btn btn-default btn-flat" onclick="setLocation('<?php echo $block->getBackUrl();?>')"><i class="fa fa-fw fa-angle-left"></i> <?php echo __("Back")?></button>
            <button class="btn btn-default btn-flat pull-right" onclick="setLocation('<?php echo $block->getDeleteUrl();?>')"><i class="fa fa-fw fa-trash-o"></i> <?php echo __("Delete")?></button>
            <button class="btn btn-default btn-flat pull-right" id="msg-reply-btn"><i class="fa fa-fw fa-reply"></i> <?php echo __("Reply")?></button>
        </div>
        <div class="box box-primary box-message-list">
            <?php echo $block->getChildHtml('message_content')?>
        </div>
        
        <div class="box box-reply-message hide">
            <div class="box-body">
                <div class="form-group">
                    <textarea name="reply" id="reply_msg_box" class="textarea admin__control-textarea" rows="2" cols="15" ></textarea>
                </div>
            </div>
            <div class="box-footer">
              <div class="pull-right">
                <?php /*?><button class="btn btn-default"><i class="fa fa-pencil"></i> <?php echo __("Draft")?></button>*/?>
                <button type="button" class="btn btn-primary" id="msg-send-btn"><i class="fa fa-envelope-o"></i> <?php echo __("Send")?></button>
              </div>
              <button class="btn btn-default" id="msg-discard-btn"><i class="fa fa-times"></i> <?php echo __("Discard")?></button>
            </div>
        </div>
        
        <div class="message-buttons message-buttons-footer hide">
            <button class="btn btn-default btn-flat reply-btn" id="msg-reply-btn-footer"><i class="fa fa-fw fa-reply"></i> <?php echo __("Reply")?></button>
        </div>
    </div>
</div>

<div class="message-notification-box hide" id="vnecoms-msg-notification"><?php echo __("Sending ...")?></div>

<script type="text/javascript">
//<![CDATA[
window.tinyMCE_GZ = window.tinyMCE_GZ || {}; window.tinyMCE_GZ.loaded = true;
require([
    "jquery",
    "Magento_Ui/js/modal/alert",
    "mage/translate",
    "Vnecoms_VendorsMessage/js/wysiwyg/tiny_mce/setup",
 ], function(jQuery, alert, $t){   
    wysiwygpage_reply_msg_box = new tinyMceWysiwygSetup(
	    "reply_msg_box",
	    {
		    "enabled":true,
		    "theme":"simple",
		    "theme_advanced_buttons1":"",
		    "theme_advanced_buttons2":"",
		    "theme_advanced_buttons3":"",
		    "theme_advanced_buttons4":"",
		    "plugins":"",
		    "width":"100%"
	    }
    );
    //jQuery(window).on("load", wysiwygpage_reply_msg_box.setup.bind(wysiwygpage_reply_msg_box, "exact"));
    wysiwygpage_reply_msg_box.turnOn();
    
    jQuery("#msg-reply-btn, #msg-reply-btn-footer").click(function(){
        jQuery(".box-reply-message").removeClass('hide');
        jQuery('html, body').animate({
            scrollTop: jQuery(".box-reply-message").offset().top
        }, 1000);
    });
    jQuery("#msg-discard-btn").click(function(){
        jQuery(".box-reply-message").addClass('hide');
        tinyMCE.get('reply_msg_box').setContent('<p></p>');
    });

    jQuery("#msg-send-btn").click(function(){
        jQuery("#vnecoms-msg-notification").removeClass('hide');
        jQuery(".box-reply-message").addClass('hide');
        jQuery.ajax({
            method: "POST",
            url: "<?php echo $block->getSendUrl();?>",
            dataType: 'json',
            data: {content: tinyMCE.get('reply_msg_box').getContent()},
            success: function (data) {
            	jQuery("#vnecoms-msg-notification").addClass('hide');
                if(data.error){
                	jQuery(".box-reply-message").removeClass('hide');
                	alert({
            			modalClass: 'alert ves-error',
                        title: '<?php echo __("Error");?>',
                        content: data.msg,
                    });
                }else{
                    /*
                    if(data.msg){
                        alert({
                            modalClass: 'alert ves-error',
                            title: '<?php echo __("Warning");?>',
                            content: data.msg,
                        });
                    }*/
                	jQuery('.box-message-list').html(data.message_list);
                	tinyMCE.get('reply_msg_box').setContent('<p></p>');
                }
            }
        });
    });

    window.buttons_top_offset = jQuery(".message-buttons").offset().top;
    
    function toggleFixedButtons(){
		if (jQuery(window).scrollTop() > window.buttons_top_offset) {
	        jQuery('.message-buttons-footer').removeClass('hide');
	    } else {
	        jQuery('.message-buttons-footer').addClass('hide');
	    }
    }
    
	jQuery(window).bind('scroll', function () {
		toggleFixedButtons();
	});
	toggleFixedButtons();
});
//]]>
</script>