<?php

namespace Vnecoms\VendorsLayerNavigation\Model\Layer\VendorHomePage;

class AvailabilityFlag extends \Magento\Catalog\Model\Layer\Category\AvailabilityFlag
{
    public function isEnabled($layer, array $filters = [])
    {

        return parent::isEnabled($layer, $filters); // TODO: Change the autogenerated stub
    }
}