<div class="all-template-content">
    <?php for($i=1;$i<=10;$i++){ ?>
        <div class="template-item">
                <h2><?php echo __('Template ').$i ?></h2>
                <img src="<?php echo $this->getViewFileUrl('Magecomp_Mobilelogin::images/'.$i.'.png'); ?>" />
        </div>
    <?php } ?>
</div>
<style>
    .all-template-content {
        float: left;
        width: 100%;
    }
    .template-item {
        border-bottom: 3px solid;
        float: left;
        padding-bottom: 15px;
        width: 100%;
    }
    .template-item h2 {
        margin: 10px 0;
    }
    .template-item > img {
        float: left;
        width: 100%;
    }
</style>