<?php $_message = $block->getMessage();?>
<?php $msgDetailCollection = $_message->getMessageDetailCollection();?>
<?php $detailCollectionSize = $msgDetailCollection->getSize();?>

<?php $i = 1;?>
<?php foreach($msgDetailCollection as $_msgDetail):?>
<div class="box-body no-padding<?php echo " message-".$i;?><?php if($i == $detailCollectionSize):?> last<?php endif?>">
    <div class="mailbox-read-info<?php if($_msgDetail->getIsRead() && $detailCollectionSize > 1 && $i != $detailCollectionSize):?> read<?php endif;?>">
        <div class="pull-left message-icon<?php if($_message->getOwnerId() == $_msgDetail->getSenderId()):?> owner-message<?php endif;?>">
            <i class="vnecoms-mfa vnecoms-mfa-user"></i>
        </div>
        <div class="pull-left">
            <?php if($_message->getOwnerId() == $_msgDetail->getSenderId()):?>
                <h3><?php echo __("me")?></h3>
            <?php else:?>
                <h3><?php echo $_msgDetail->getSenderName()?></h3> <span>&lt;<?php echo $_msgDetail->getSenderEmail()?>&gt;</span>
            <?php endif;?>
            <div class="text-muted"><?php echo __("to %1",$_message->getOwnerId() == $_msgDetail->getReceiverId()?__("me"):$_msgDetail->getReceiverName().sprintf(" &lt;%s&gt;",$_msgDetail->getReceiverEmail()))?></div>
        </div>
        
        <div class="pull-right">
            <span class="mailbox-read-time pull-right"><?php echo $block->formatDate($_msgDetail->getCreatedAt(),\IntlDateFormatter::MEDIUM,\IntlDateFormatter::MEDIUM)?></span>
        </div>
    </div>
    <div class="mailbox-read-message<?php if($_msgDetail->getIsRead() && $detailCollectionSize > 1 && $i != $detailCollectionSize):?> hide<?php endif;?>">
        <?php echo $_msgDetail->getContent();?>
    </div>
</div>
<?php $i++;?>
<?php endforeach;?>
<?php if($detailCollectionSize > 1):?>
<script type="text/javascript">
require(["jquery"], function($){
    $(function() {
        $('.mailbox-read-info').click(function(){
            if(!$(this).parent().hasClass('last')){
            	$(this).toggleClass("read");
                $(this).siblings('.mailbox-read-message').toggleClass("hide");
            }
        })
    });
});
</script>
<?php endif;?>