<?php
/**
 * Category view template
 *
 * @var $block \Vnecoms\VendorsMessage\Block\Message
 */
$_vendor = $block->getVendor();
?>
<div class="new-message-container hide" id="new-message-container">
    <div class="block block-new-message">
        <div class="block-title"><strong><?php echo __("New Message")?></strong></div>
        <div class="block-content">
            <form id="new-msg-form">
                <fieldset class="fieldset info">
                    <div class="field">
                        <label class="label" for="firstname">
                            <span><?php echo __("Recipient")?></span>
                        </label>
                        <div class="control">
                            <span><?php echo $_vendor->getVendorId()?></span>
                        </div>
                    </div>
                    <div class="field required">
                        <label class="label" for="firstname">
                            <span><?php echo __("Subject")?></span>
                        </label>
                        <div class="control">
                            <input id="msg_subject" name="message[subject]" value="" title="<?php echo __("Subject")?>" class="input-text" type="text"  data-validate="{required:true}">
                        </div>
                    </div>
                    <div class="field required">
                        <div class="control">
                            <textarea name="message[content]" id="msg_content" class="textarea input-text" rows="2" cols="15" data-validate="{required:true}"></textarea>
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <div class="send-btn-container">
                            <button type="button" class="vnecoms-mfa vnecoms-mfa-envelope-o action save primary" id="new-msg-send-btn" title="<?php echo __("Send")?>"><span> <?php echo __("Send")?></span></button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
        <div class="block-control"><a href="javascript: void(0)" class="close-btn" id="new-msg-close-btn"><i class="vnecoms-mfa vnecoms-mfa-discard"></i></a></div>
        <script type="text/javascript">
        //<![CDATA[
        window.tinyMCE_GZ = window.tinyMCE_GZ || {}; window.tinyMCE_GZ.loaded = true;
        require([
            "jquery",
            "Magento_Ui/js/modal/alert",
            "mage/translate",
            "Vnecoms_VendorsMessage/js/wysiwyg/tiny_mce/setup",
         ], function(jQuery, alert){
            /*Init wysiwyg*/
            wysiwygpage_msg_content = new tinyMceWysiwygSetup(
        	    "msg_content",
        	    {
            	    "enabled":true,
            	    "theme":"simple",
            	    "theme_advanced_buttons1":"bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,outdent,indent",
            	    "theme_advanced_buttons2":"",
            	    "theme_advanced_buttons3":"",
            	    "theme_advanced_buttons4":"",
            	    "plugins":"",
            	    "width":"100%"
        	    }
            );
            /* jQuery(window).on("load", wysiwygpage_msg_content.setup.bind(wysiwygpage_msg_content, "exact")); */
            wysiwygpage_msg_content.turnOn();
            /*Message button in profile block  */
            jQuery("#vnecoms-msg-btn").click(function(){
                <?php if($block->isLoggedIn() && $block->canSendMessage()):?>
                    jQuery("#new-message-container").removeClass("hide");
                <?php else:?>
                    <?php if(!$block->isLoggedIn()){$title = __("Login Required"); $msg = __("You need to login to use this feature.");} else{$title = __("Error"); $msg = __("You can not send message to your self.");}?>
                    alert({
            			modalClass: 'alert ves-error',
                        title: '<?php echo $title;?>',
                        content: '<?php echo $msg;?>',
                    });
                <?php endif;?>
            });

            /*Close button click*/
            jQuery("#new-msg-close-btn").click(function(){
            	jQuery("#new-message-container").addClass("hide");
            });

            /*Send message*/
            jQuery("#new-msg-send-btn").click(function(){
            	if(dataForm.valid()){
                	if(!jQuery('#msg_content').val()){
                		alert({
                			modalClass: 'alert ves-error',
                            title: '<?php echo __("Error...");?>',
                            content: '<?php echo __("Please enter your message body.");?>',
                        });
                        return;
                	}
                	jQuery('#vnecoms-msg-notification').removeClass('hide');
                	jQuery("#new-message-container").addClass('hide');
            		jQuery.ajax({
                        method: "POST",
                        url: "<?php echo $block->getSendUrl();?>",
                        data: {subject: jQuery("#msg_subject").val(),content: tinyMCE.get('msg_content').getContent()}
                    }).done(function( msg ) {
                    	jQuery('#vnecoms-msg-notification').addClass('hide');
                        jQuery("#msg_subject").val('');
                        tinyMCE.get('msg_content').setContent('<p></p>');
                    });
            	}
            });

            var dataForm = jQuery('#new-msg-form');            
            dataForm.mage('validation');
        });
        //]]>
        </script>
    </div>
</div>

<div class="message-notification-box hide" id="vnecoms-msg-notification"><?php echo __("Sending ...")?></div>