<li class="dropdown messages-menu">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	  <i class="fa fa-envelope-o"></i>
	  <span class="label label-success"><?php echo $block->getUnreadMessageCount();?></span>
	</a>
	<ul class="dropdown-menu">
        <li class="header"><?php echo __("You have %1 messages",$block->getUnreadMessageCount())?></li>
        <li>
    		<ul class="menu">
            <?php foreach($block->getUnreadMessageCollection() as $message):?>
                <?php $detail = $message->getLastMessageDetail();?>
                <li><!-- start message -->
                <a href="<?php echo $block->getViewMessageUrl($message)?>">
                  <div class="pull-left">
                    <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/user.png')?>" class="img-circle" alt="User Image">
                  </div>
                  <h4>
                    <?php echo $detail->getSenderName()?>
                    <small><i class="fa fa-clock-o"></i> <?php echo $block->getMessageTime($detail->getCreatedAt());?></small>
                  </h4>
                  <p><?php echo $detail->getSubject()?></p>
                </a>
                </li><!-- end message -->
            <?php endforeach;?>
    		</ul>
        </li>
        <li class="footer"><a href="<?php echo $block->getMessageUrl();?>"><?php echo __('See All Messages')?></a></li>
	</ul>
</li>
