<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<hr />
<h3><?php echo __("Additional Information")?></h3>
<?php $withdrawal = $block->getData("withdrawal") ?>
<?php $additionalInfo = unserialize($withdrawal->getAdditionalInfo());?>
<?php foreach($additionalInfo as $info):?>
    <strong><?php echo $info['label']?>:</strong> <?php echo $info['value']?> <br />
<?php endforeach;?>
