<?php

namespace Vnecoms\VendorsPage\Block\Navigation;

use Magento\Catalog\Model\Layer\Filter\FilterInterface;
use Magento\Framework\View\Element\Template;
use Magento\LayeredNavigation\Block\Navigation\FilterRendererInterface;

class FilterRenderer extends \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
{
    public function render(FilterInterface $filter)
    {
        //if($filter->getName() == __('Category 11')) return '';
        return parent::render($filter); // TODO: Change the autogenerated stub
    }
}
